version: '3.8'

volumes:
  postgres_data:  # Esta declaração deve vir antes dos services

services:
  db:
    image: postgres:13-alpine
    container_name: sitecompras-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sitecompras
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5